# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Terraform Cloud Action
description: 'Use this action to create AND DESTROY infrastructure within a single workflow.'
inputs:
  hostname:
    required: false
    default: 'app.terraform.io'
  token:
    description: "The Terraform Cloud/Terraform Enterprise access token."
    required: true
  organization:
    description: "The Terraform Cloud/Terraform Enterprise organization that owns the specified workspace."
    required: true
  workspace:
    description: "The Terraform Cloud/Terraform Enterprise workspace to fetch outputs from."
    required: true
  cleanup:
    description: "If set to true, the action will run a DESTROY PLAN on the workspace at the end of the workflow."
    required: true
  auto-apply:
    description: "If set to true, applies changes when a Terraform plan is successful. Defaults to true."
    required: false
    default: true
  message:
    required: false
    description: "A custom message to associate with the run."
    default: "Run created by GitHub action"
  replace-addrs:
    description: "Multi-line list of resource addresses to be replaced. Use one address per line."
    required: false
  target-addrs:
    description: "Multi-line list of resource addresses that Terraform should focus its planning efforts on. Use one address per line."
    required: false

outputs:
  run-id:
    description: "The id of the apply run"
  workspace-outputs-json:
    description: "The new workspace outputs, expressed as a JSON string, after the apply run. Use fromJSON to decode."

runs:
  using: 'node16'
  main: './dist/workflow/index.js'
  post: './dist/destroy/index.js'
