# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: HCP Terraform Apply
description: "Creates a standard plan/apply run on the specifed HCP Terraform/Terraform Enterprise workspace"
runs:
  using: "node20"
  main: "../dist/apply/index.js"
inputs:
  hostname:
    required: false
    default: "app.terraform.io"
    description: "The Terraform Enterprise hostname. Defaults to app.terraform.io (HCP Terraform)."
  token:
    description: "The HCP Terraform/Terraform Enterprise access token."
    required: true
  organization:
    description: "The HCP Terraform/Terraform Enterprise organization that owns the specified workspace."
    required: true
  workspace:
    description: "The HCP Terraform/Terraform Enterprise workspace to fetch outputs from."
    required: true
  wait:
    description: "If set, waits for the run to terminate and resources to be processed before the action finishes. Defaults to true."
    required: false
    default: "true"
  auto-apply:
    description: "If set, applies changes when a Terraform plan is successful. Defaults to true."
    required: false
    default: "true"
  is-destroy:
    description: "If set, a destroy plan will be run. Defaults to false."
    required: false
    default: "false"
  message:
    required: false
    description: "A custom message to associate with the run."
    default: "Run created by GitHub action"
  replace-addrs:
    description: "Multi-line list of resource addresses to be replaced. Use one address per line."
    required: false
  target-addrs:
    description: "Multi-line list of resource addresses that Terraform should focus its planning efforts on. Use one address per line."
outputs:
  run-id:
    description: "The id of the run that was created"
