name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mockinfra:
    - uses: ./
      with:
        cleanup: true
        token: ${{ secrets.TFC_TOKEN }}
        organization: bcroft
        workspace: test-terraform-apply-action
      outputs:
        workspace-outputs-json: ${{ steps.fetch.outputs.workspace-outputs-json }}

  e2e:
    runs-on: "ubuntu-latest"
    name: "E2E Testing"
    needs: [ mockinfra ]
    steps:
      - name: Expectations
      - run: |
      echo ${{ fromJSON(needs.mockinfra.outputs.workspace-outputs-json) }}
      sh -c '[[ "${{ fromJSON(needs.mockinfra.outputs.workspace-outputs-json).string }}" = "string" ]] && echo PASS || echo FAIL && exit 1'

  lint-test:
    runs-on: "ubuntu-latest"
    name: "List & Test"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: npm ci
        run: npm ci

      - name: Format Check
        run: npm run format-check

      - name: Verify
        run: |
          npm run build
          # Fail if "npm run build" generated new changes in dist
          git update-index --refresh dist/* && git diff-index --quiet HEAD dist

      - name: Test
        run: npm run test
